name: meal_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_native_splash: ^2.4.0
  http: ^1.2.2
  loading_animation_widget:
  persistent_bottom_nav_bar: ^6.2.1
  water_drop_nav_bar: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hutao.png
    - assets/brand.png